version: '3.8'

services:
  index:
    build: .
    container_name: index-container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - webnet
    depends_on:
      - server  # Assegura que o contêiner do servidor esteja disponível antes de iniciar o contêiner index

  server:
    build: src/server/.
    container_name: server-container
    ports:
      - "8101:8101"
    volumes:
      - ./src/server:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
